### ISSUE TITLE
feat: チャット一覧画面

### ISSUE THREAD

**Issue by shuto1234** [Team-Futsukayoi/Nomikai-Setting-App#16]

**Comment by Minoru-kuma** [comment]
- 追加したい機能
　- 使用しているユーザーのフレンド、グループ一覧表示
　- ユーザーのプロフィール画面への遷移
　- グループ作成画面への遷移
　- フレンド追加画面への遷移
-必要なプロパティ
　-アカウントID
　-アカウント名
　-所属グループリスト
　-フレンドリスト
